export enum ControlTypesEnum {
    TEXT = 'text',
    TEXT_UPPERCASE = 'text:upperCase',
    TEXT_CAPITALIZE = 'text:capitalize',
    TEXT_LOWERCASE = 'text:lowerCase',
    PKEY = 'pkey',
    LONGTEXT = 'longText',
    DROPDOWN = 'dropdown',
    DATE = 'date',
    EDITABLEDATE = 'editableDate',
    TIME = 'time',
    BOOLEAN = 'boolean',
    IMAGE = 'image',
    PRICE = 'price',
    PERCENT = 'percent',
    EMAIL = 'email',
    AUTOCOMPLETE = 'autocomplete',
    ARRAY = 'array',
    NUMERIC = 'numeric',
    INT = 'int',
    FORM = 'form',
    CHIPS = 'chips',
    BUTTON= 'buttonTable',
    CHECK= 'check',
    BUILD = 'build',
    EXPAND = 'expand'
  }